DEBUG = False
YAW_THRESHOLD = 0.03    #radians
REPULSION_SAFE_THRESHOLD = 0.001
WP_THRESHOLD = 1.0
WALL_REPULSION_RADIUS = 1.5
OBSTACLE_REPULSION_RADIUS = 1.3
THROTTLE = 4.5
LOOKAHEAD_DISTANCE = 0.8
P_GAIN = 6.0
alpha = 0.1

MAX_STEER_VAL = 10
REPULSION_GAIN = 2
BACK_THROTTLE = 2.5
WALL_REPULSION_STRENGTH = 150
OBSTACLE_REPULSION_STRENGTH = 2.75
REPULSION_BACK_THRESHOLD = 8

MAX_STEER_VAL_ALIGN = 10
ALIGN_THROTTLE = 3
ALIGN_REPULSION_GAIN = 2.0
WALL_REPULSION_STRENGTH_ALIGN = 800
OBSTACLE_REPULSION_STRENGTH_ALIGN = 20
REPULSION_BACK_THRESHOLD_ALIGN = 0.5